export const data = [
  {
    uuid: '1',
    name: 'T1  (Douche)',
    nb_evier: 1,
    nb_vasque: 1,
    nb_douche: 1,
    nb_baignoire: 0,
    prive40: 75,
    social40: 75,
    coeffPrive: 0.6,
    coeffSocial: 0.6,
    coeffQualitel: 0.8
  },
  {
    uuid: '2',
    name: 'T1 (baignoire)',
    nb_evier: 1,
    nb_vasque: 1,
    nb_douche: 0,
    nb_baignoire: 1,
    prive40: 75,
    social40: 75,
    coeffPrive: 0.6,
    coeffSocial: 0.6,
    coeffQualitel: 0.8
  },
  {
    uuid: '4',
    name: 'T2 (baignoire)',
    nb_evier: 1,
    nb_vasque: 1,
    nb_douche: 0,
    nb_baignoire: 1,
    prive40: 80,
    social40: 80,
    coeffPrive: 0.7,
    coeffSocial: 0.7,
    coeffQualitel: 0.9
  },
  {
    uuid: '3',
    name: 'T2 (douche)',
    nb_evier: 1,
    nb_vasque: 1,
    nb_douche: 1,
    nb_baignoire: 0,
    prive40: 80,
    social40: 80,
    coeffPrive: 0.7,
    coeffSocial: 0.7,
    coeffQualitel: 0.9
  },
  {
    uuid: '5',
    name: 'T3 (baignoire)',
    nb_evier: 1,
    nb_vasque: 1,
    nb_douche: 0,
    nb_baignoire: 1,
    prive40: 100,
    social40: 110,
    coeffPrive: 0.9,
    coeffSocial: 1,
    coeffQualitel: 1
  },
  {
    uuid: '6',
    name: 'T3 (une baignoire et une douche)',
    nb_evier: 1,
    nb_vasque: 2,
    nb_douche: 1,
    nb_baignoire: 1,
    prive40: 100,
    social40: 110,
    coeffPrive: 0.9,
    coeffSocial: 1,
    coeffQualitel: 1.2
  },
  {
    uuid: '7',
    name: 'T4 (une baignoire)',
    nb_evier: 1,
    nb_vasque: 2,
    nb_douche: 0,
    nb_baignoire: 2,
    prive40: 110,
    social40: 145,
    coeffPrive: 1,
    coeffSocial: 1.4,
    coeffQualitel: 1
  },
  {
    uuid: '8',
    name: 'T4 (une baignoire et une douche)',
    nb_evier: 1,
    nb_vasque: 2,
    nb_douche: 1,
    nb_baignoire: 1,
    prive40: 110,
    social40: 145,
    coeffPrive: 1,
    coeffSocial: 1.4,
    coeffQualitel: 1.2
  },
  {
    uuid: '9',
    name: 'T5 / T6 (une baignoire)',
    nb_evier: 1,
    nb_vasque: 2,
    nb_douche: 0,
    nb_baignoire: 1,
    prive40: 140,
    social40: 190,
    coeffPrive: 1.3,
    coeffSocial: 1.8,
    coeffQualitel: 1.2
  },
  {
    uuid: '10',
    name: 'T5 / T6 (une baignoire et une douche)',
    nb_evier: 1,
    nb_vasque: 3,
    nb_douche: 1,
    nb_baignoire: 1,
    prive40: 140,
    social40: 190,
    coeffPrive: 1.4,
    coeffSocial: 1.9,
    coeffQualitel: 1.3
  },
  {
    uuid: '11',
    name: 'T5 / T6 (deux baignoires)',
    nb_evier: 1,
    nb_vasque: 4,
    nb_douche: 0,
    nb_baignoire: 2,
    prive40: 170,
    social40: 220,
    coeffPrive: 1.4,
    coeffSocial: 1.9,
    coeffQualitel: 1.4
  }
];
