export default  [
{value : "PLAFOND3",
         label :  "Ardoise"},
{value : "PLAFOND1",
         label :  "Béton"},
{value : "PLAFOND7",
         label :  "Faux plafond lame d'air + enduit platre ou BA13"},
{value : "PLAFOND4",
         label :  "Plancher LEADER"},
{value : "PLAFOND0",
         label :  "Plâtre"},
{value : "PLAFOND8",
         label :  "Toit ardoise/Zinc non isolé"},
{value : "PLAFOND5",
         label :  "Toit terrasse béton non isolé"},
{value : "PLAFOND6",
         label :  "Toit terrasse Siporex 20"},
{value : "PLAFOND2",
         label :  "Tuile"},
];