export default  [
{value : "ilosant21",
         label :  "Botte de paille (flux parallèle aux fibres)"},
{value : "ilosant20",
         label :  "Botte de paille (flux perpendiculaire aux fibres)"},
{value : "ilosant27",
         label :  "Chanvre + chaux"},
{value : "ilosant26",
         label :  "Chanvre en vrac"},
{value : "ilosant19",
         label :  "Feutre bitumeux"},
{value : "ilosant24",
         label :  "Fibre de cellulose"},
{value : "ilosant22",
         label :  "Laine de lin"},
{value : "ilosant23",
         label :  "Laine de mouton"},
{value : "ilosant4",
         label :  "Laine de roche"},
{value : "ilosant8",
         label :  "Laine de roche en vrac"},
{value : "ilosant11",
         label :  "Laine de verre (densité faible)"},
{value : "ilosant9",
         label :  "Laine de verre (densité forte)"},
{value : "ilosant10",
         label :  "Laine de verre (densité moyenne)"},
{value : "ilosant5",
         label :  "Lame d'air"},
{value : "ilosant7",
         label :  "Mousse polyuréthane Sol"},
{value : "ilosant25",
         label :  "Panneau de roseaux"},
{value : "ilosant28",
         label :  "Panneaux laine de bois"},
{value : "ilosant29",
         label :  "Panneaux laine de bois léger"},
{value : "ilosant13",
         label :  "Polycarbonate"},
{value : "ilosant1",
         label :  "Polystyrène expansé"},
{value : "ilosant12",
         label :  "Polystyrène extrudé"},
{value : "ilosant2",
         label :  "Polystyrène extrudé"},
{value : "ilosant0",
         label :  "Polyuréthane"},
{value : "ilosant14",
         label :  "Polyéthylène basse densité"},
{value : "ilosant6",
         label :  "PSE prégymax"},
{value : "ilosant15",
         label :  "PVC"},
{value : "ilosant3",
         label :  "Vermiculite"},
{value : "ilosant17",
         label :  "Verre cellulaire"},
{value : "ilosant18",
         label :  "Verre cellulaire (plaque)"},
{value : "ilosant16",
         label :  "Verre cellulaire Foamglass"},
];