export default  [
{value : "ecs4",
         label :  "Buanderie"},
{value : "ecs18",
         label :  "Bureaux"},
{value : "ecs8",
         label :  "Camping 4*"},
{value : "ecs3",
         label :  "Cantine/Cuisine"},
{value : "ecs11",
         label :  "Cuisine Maison de retraite"},
{value : "ecs12",
         label :  "Ecole"},
{value : "ecs9",
         label :  "Foyers chambres individuelles"},
{value : "ecs15",
         label :  "Gymnases"},
{value : "ecs21",
         label :  "Hopital et maternité"},
{value : "ecs5",
         label :  "Hôtel 1* "},
{value : "ecs6",
         label :  "Hôtel 2 ou 3* "},
{value : "ecs7",
         label :  "Hôtel 4ou 5*"},
{value : "ecs13",
         label :  "Internat ou Caserne "},
{value : "ecs10",
         label :  "Maison de retraite"},
{value : "ecs17",
         label :  "Piscine avec douches"},
{value : "ecs1",
         label :  "Restaurant"},
{value : "ecs2",
         label :  "Restaurant de luxe"},
{value : "ecs16",
         label :  "Stades"}
];