export default  [
{value : "Porte3",
         label :  "Aluminium "},
{value : "PLAFOND3",
         label :  "Ardoise"},
{value : "MEXT12",
         label :  "Basalte"},
{value : "Porte1",
         label :  "Bois isolante"},
{value : "Porte0",
         label :  "Bois pleine"},
{value : "MEXT32",
         label :  "Bois très lourds"},
{value : "ilosant21",
         label :  "Botte de paille (flux parallèle aux fibres)"},
{value : "ilosant20",
         label :  "Botte de paille (flux perpendiculaire aux fibres)"},
{value : "MEXT4",
         label :  "Briq. Creu. Alvéol."},
{value : "MEXT3",
         label :  "Briq. Creu. Class."},
{value : "MEXT25",
         label :  "Brique creuse de 10"},
{value : "MEXT26",
         label :  "Brique creuse de 5"},
{value : "MEXT27",
         label :  "Brique creuse de 7,5"},
{value : "MEXT28",
         label :  "Brique Gelis 30"},
{value : "MEXT31",
         label :  "Brique Gelis 37,5 isomortier"},
{value : "MEXT30",
         label :  "Brique Gélis 37,5 isolant Gelis"},
{value : "MEXT29",
         label :  "Brique Gélis 37,5 mortier classique"},
{value : "MEXT5",
         label :  "Brique pleine"},
{value : "MEXT20",
         label :  "Briques alvéoles 25"},
{value : "MEXT21",
         label :  "Briques alvéoles 37,5"},
{value : "MEXT22",
         label :  "Briques alvéoles Sturm 30"},
{value : "MEXT23",
         label :  "Briques alvéoles Sturm 37"},
{value : "MEXT24",
         label :  "Briques Argelis 20"},
{value : "Plancher1",
         label :  "Béton"},
{value : "PLAFOND1",
         label :  "Béton"},
{value : "MEXT2",
         label :  "Béton"},
{value : "MEXT33",
         label :  "Béton de copeaux de bois"},
{value : "MEXT34",
         label :  "Béton de fibres de bois"},
{value : "Plancher12",
         label :  "Caisson chevronné 120"},
{value : "MEXT14",
         label :  "Calcaire Pierre dure"},
{value : "MEXT15",
         label :  "Calcaire Pierre tendre"},
{value : "MEXT16",
         label :  "Calcaire Pierre très tendre"},
{value : "Plancher19",
         label :  "Carrelage grès"},
{value : "Plancher20",
         label :  "Carrelage Marbre"},
{value : "Plancher18",
         label :  "Carrelage terre cuite"},
{value : "ilosant27",
         label :  "Chanvre + chaux"},
{value : "ilosant26",
         label :  "Chanvre en vrac"},
{value : "Plancher6",
         label :  "Dalle béton coulé"},
{value : "Plancher13",
         label :  "Dalle Siporex 15"},
{value : "Plancher16",
         label :  "Dalle Siporex 15"},
{value : "Plancher14",
         label :  "Dalle Siporex 20"},
{value : "Plancher15",
         label :  "Dalle Siporex 25"},
{value : "Plancher2",
         label :  "Entrevous brique"},
{value : "Plancher3",
         label :  "Entrevous béton"},
{value : "PLAFOND7",
         label :  "Faux plafond lame d'air + enduit platre ou BA13"},
{value : "ilosant19",
         label :  "Feutre bitumeux"},
{value : "ilosant24",
         label :  "Fibre de cellulose"},
{value : "MEXT11",
         label :  "Granite"},
{value : "Plancher7",
         label :  "Hourdi béton 12"},
{value : "Plancher8",
         label :  "Hourdi béton 16"},
{value : "Plancher9",
         label :  "Hourdi béton 20"},
{value : "Plancher10",
         label :  "Hourdi béton 25"},
{value : "Plancher11",
         label :  "Hourdi PPB Iso5 4"},
{value : "ilosant22",
         label :  "Laine de lin"},
{value : "ilosant23",
         label :  "Laine de mouton"},
{value : "ilosant4",
         label :  "Laine de roche"},
{value : "Plancher17",
         label :  "Laine de roche compressé 10"},
{value : "ilosant8",
         label :  "Laine de roche en vrac"},
{value : "ilosant11",
         label :  "Laine de verre (densité faible)"},
{value : "ilosant9",
         label :  "Laine de verre (densité forte)"},
{value : "ilosant10",
         label :  "Laine de verre (densité moyenne)"},
{value : "ilosant5",
         label :  "Lame d'air"},
{value : "MEXT10",
         label :  "Marbre, Gneiss, Porphyre"},
{value : "MEXT17",
         label :  "Meulière lourde"},
{value : "MEXT18",
         label :  "Meulière légère, Grès"},
{value : "MEXT1",
         label :  "Mortier"},
{value : "ilosant7",
         label :  "mousse polyu. Sol"},
{value : "MEXT35",
         label :  "Panneau bois liant hydraulique"},
{value : "ilosant25",
         label :  "Panneau de roseaux"},
{value : "ilosant28",
         label :  "Panneaux laine de bois"},
{value : "ilosant29",
         label :  "Panneaux laine de bois léger"},
{value : "MEXT6",
         label :  "Parpaing < 20cm"},
{value : "MEXT7",
         label :  "Parpaing > 20 cm"},
{value : "MEXT9",
         label :  "Pierre dure"},
{value : "MEXT8",
         label :  "Pierre tendre"},
{value : "Plancher4",
         label :  "plancher LEADER"},
{value : "PLAFOND4",
         label :  "plancher LEADER"},
{value : "Plancher5",
         label :  "Plancher non isolé"},
{value : "MEXT0",
         label :  "Plâtre"},
{value : "PLAFOND0",
         label :  "Plâtre"},
{value : "Plancher0",
         label :  "Plâtre"},
{value : "ilosant13",
         label :  "Polycarbonate"},
{value : "ilosant1",
         label :  "Polyst. Expansé"},
{value : "ilosant2",
         label :  "Polyst. Extrudé"},
{value : "ilosant12",
         label :  "Polystyrène extrudé"},
{value : "ilosant0",
         label :  "Polyuréthane"},
{value : "ilosant14",
         label :  "Polyéthylène basse densité"},
{value : "MEXT19",
         label :  "Ponce naturelle"},
{value : "ilosant6",
         label :  "PSE prégymax"},
{value : "ilosant15",
         label :  "PVC"},
{value : "Porte2",
         label :  "PVC"},
{value : "PLAFOND8",
         label :  "Toit ardoise/Zinc non isolé"},
{value : "PLAFOND5",
         label :  "Toit terrasse béton non isolé"},
{value : "PLAFOND6",
         label :  "Toit terrasse Siporex 20"},
{value : "PLAFOND2",
         label :  "Tuile"},
{value : "Ventil0",
         label :  "Ventilation naturelle"},
{value : "ilosant3",
         label :  "Vermiculite"},
{value : "ilosant17",
         label :  "Verre cellulaire"},
{value : "ilosant18",
         label :  "Verre cellulaire (plaque)"},
{value : "ilosant16",
         label :  "Verre cellulaire Foamglass"},
{value : "Ventil1",
         label :  "VMC classique"},
{value : "Ventil2",
         label :  "VMC hygro"}
];