export default  [
{value : "MEXT12",
         label :  "Basalte"},
{value : "MEXT32",
         label :  "Bois très lourds"},
{value : "MEXT4",
         label :  "Brique Creuse Alvéolaires"},
{value : "MEXT3",
         label :  "Brique Creuse Classique"},
{value : "MEXT25",
         label :  "Brique creuse de 10"},
{value : "MEXT26",
         label :  "Brique creuse de 5"},
{value : "MEXT27",
         label :  "Brique creuse de 7,5"},
{value : "MEXT28",
         label :  "Brique Gelis 30"},
{value : "MEXT31",
         label :  "Brique Gelis 37,5 isomortier"},
{value : "MEXT30",
         label :  "Brique Gélis 37,5 isolant Gelis"},
{value : "MEXT29",
         label :  "Brique Gélis 37,5 mortier classique"},
{value : "MEXT5",
         label :  "Brique pleine"},
{value : "MEXT20",
         label :  "Briques alvéoles 25"},
{value : "MEXT21",
         label :  "Briques alvéoles 37,5"},
{value : "MEXT22",
         label :  "Briques alvéoles Sturm 30"},
{value : "MEXT23",
         label :  "Briques alvéoles Sturm 37"},
{value : "MEXT24",
         label :  "Briques Argelis 20"},
{value : "MEXT2",
         label :  "Béton"},
{value : "MEXT33",
         label :  "Béton de copeaux de bois"},
{value : "MEXT34",
         label :  "Béton de fibres de bois"},
{value : "MEXT14",
         label :  "Calcaire Pierre dure"},
{value : "MEXT15",
         label :  "Calcaire Pierre tendre"},
{value : "MEXT16",
         label :  "Calcaire Pierre très tendre"},
{value : "MEXT11",
         label :  "Granite"},
{value : "MEXT10",
         label :  "Marbre, Gneiss, Porphyre"},
{value : "MEXT17",
         label :  "Meulière lourde"},
{value : "MEXT18",
         label :  "Meulière légère, Grès"},
{value : "MEXT1",
         label :  "Mortier"},
{value : "MEXT35",
         label :  "Panneau bois liant hydraulique"},
{value : "MEXT6",
         label :  "Parpaing < 20cm"},
{value : "MEXT7",
         label :  "Parpaing > 20 cm"},
{value : "MEXT9",
         label :  "Pierre dure"},
{value : "MEXT8",
         label :  "Pierre tendre"},
{value : "MEXT0",
         label :  "Plâtre"},
{value : "MEXT19",
         label :  "Ponce naturelle"},
];