export default  [
{value : "Plancher1",
         label :  "Béton"},
{value : "Plancher12",
         label :  "Caisson chevronné 120"},
{value : "Plancher19",
         label :  "Carrelage grès"},
{value : "Plancher20",
         label :  "Carrelage Marbre"},
{value : "Plancher18",
         label :  "Carrelage terre cuite"},
{value : "Plancher6",
         label :  "Dalle béton coulé"},
{value : "Plancher13",
         label :  "Dalle Siporex 15"},
{value : "Plancher16",
         label :  "Dalle Siporex 15"},
{value : "Plancher14",
         label :  "Dalle Siporex 20"},
{value : "Plancher15",
         label :  "Dalle Siporex 25"},
{value : "Plancher2",
         label :  "Entrevous brique"},
{value : "Plancher3",
         label :  "Entrevous béton"},
{value : "Plancher7",
         label :  "Hourdi béton 12"},
{value : "Plancher8",
         label :  "Hourdi béton 16"},
{value : "Plancher9",
         label :  "Hourdi béton 20"},
{value : "Plancher10",
         label :  "Hourdi béton 25"},
{value : "Plancher11",
         label :  "Hourdi PPB Iso5 4"},
{value : "Plancher17",
         label :  "Laine de roche compressé 10"},
{value : "Plancher4",
         label :  "plancher LEADER"},
{value : "Plancher5",
         label :  "Plancher non isolé"},
{value : "Plancher0",
         label :  "Plâtre"},
];