export default  [
{value : "9",
         label :  "Bac à laver"},
{value : "4",
         label :  "Baignoire"},
{value : "3",
         label :  "Bidet"},
{value : "5",
         label :  "Douche"},
{value : "1",
         label :  "Evier"},
{value : "2",
         label :  "Lavabo"},
{value : "8",
         label :  "Lave mains"},
{value : "11",
         label :  "Machine à laver la vaisselle"},
{value : "10",
         label :  "Machine à laver le linge"},
{value : "6",
         label :  "Poste d'eau robinet 1/2"},
{value : "7",
         label :  "Poste d'eau robinet 3/4"}
];