export default  [
{value : "1",
         label :  "T1  (Douche)"},
{value : "2",
         label :  "T1 (baignoire)"},
{value : "4",
         label :  "T2 (baignoire)"},
{value : "3",
         label :  "T2 (douche)"},
{value : "5",
         label :  "T3 (baignoire)"},
{value : "6",
         label :  "T3 (une baignoire et une douche)"},
{value : "8",
         label :  "T4 (une baignoire et une douche)"},
{value : "7",
         label :  "T4 (une baignoire)"},
{value : "11",
         label :  "T5 / T6 (deux baignoires)"},
{value : "10",
         label :  "T5 / T6 (une baignoire et une douche)"},
{value : "9",
         label :  "T5 / T6 (une baignoire)"}
];