export default  [
{value : "aa16",
         label :  "Chaudière"},
{value : "aa15",
         label :  "Convecteur"},
{value : "aa3",
         label :  "Coude 90 r/d4="},
{value : "aa1",
         label :  "Coude 90 r/d=1"},
{value : "aa2",
         label :  "Coude 90 r/d=2"},
{value : "aa14",
         label :  "Radiateur"},
{value : "aa13",
         label :  "Robinet thermostatique"},
{value : "aa7",
         label :  "Té-amené coudé"},
{value : "aa6",
         label :  "Té-amené droit"},
{value : "aa9",
         label :  "Té-convergence"},
{value : "aa5",
         label :  "Té-départ coudé"},
{value : "aa4",
         label :  "Té-départ droit"},
{value : "aa11",
         label :  "Té-oblique coudé 45"},
{value : "aa10",
         label :  "Té-oblique droit"},
{value : "aa8",
         label :  "Té-séparation"},
{value : "aa17",
         label :  "Vanne 3 voies"},
{value : "aa12",
         label :  "Vanne … passage directe"}
];