export default  [
{value : "ENER15",
         label :  "Chaudière bois déchiqueté"},
{value : "ENER4",
         label :  "Chaudières bois buche"},
{value : "ENER6",
         label :  "Chaudières bois granulé domestique"},
{value : "ENER5",
         label :  "Chaudières à bois granulé vrac"},
{value : "ENER1",
         label :  "Electrique"},
{value : "ENER7",
         label :  "Fioul BT"},
{value : "ENER8",
         label :  "Fioul Condensation"},
{value : "ENER11",
         label :  "Gaz naturel BT"},
{value : "ENER12",
         label :  "Gaz naturel condensation"},
{value : "ENER2",
         label :  "PAC Air/eau"},
{value : "ENER3",
         label :  "PAC Eau/eau"},
{value : "ENER17",
         label :  "Poile fioul domestique"},
{value : "ENER9",
         label :  "Propane BT"},
{value : "ENER10",
         label :  "Propane condensation"},
{value : "ENER16",
         label :  "Solaire"},
{value : "ENER14",
         label :  "Très vieille chaudière fioul"},
{value : "ENER13",
         label :  "Très vieille chaudière gaz"}
];