export default  [
{value : "acier1",
         label :  "Acier 1 panneau (type 10)"},
{value : "acier2",
         label :  "Acier 1 panneau, 1 rang d'ailettes (type 11)"},
{value : "acier3",
         label :  "Acier 2 panneaux (type 20)"},
{value : "acier4",
         label :  "Acier 2 panneaux, 1 rang d'ailettes (type 21)"},
{value : "acier5",
         label :  "Acier 2 panneaux, 2 rangs d'ailettes (type 22)"},
{value : "acier6",
         label :  "Acier 3 panneaux (type 30)"},
{value : "acier7",
         label :  "Acier 3 panneaux, 2 rangs d'ailettes (type 32)"},
{value : "alu1",
         label :  "Alu 350/100"},
{value : "alu2",
         label :  "Alu 500/80 A3"},
{value : "alu3",
         label :  "Alu 600/80 A3"},
{value : "alu4",
         label :  "Alu 700/80"},
{value : "alu5",
         label :  "Alu 800/80"},
{value : "fonte1",
         label :  "Fonte"}
];