export default  [
{value : "acier1",
         label :  "Acier 1 panneau (type 10)"},
{value : "acier2",
         label :  "Acier 1 panneau, 1 rang d'ailettes (type 11)"},
{value : "acier3",
         label :  "Acier 2 panneaux (type 20)"},
{value : "acier4",
         label :  "Acier 2 panneaux, 1 rang d'ailettes (type 21)"},
{value : "acier5",
         label :  "Acier 2 panneaux, 2 rangs d'ailettes (type 22)"},
{value : "acier6",
         label :  "Acier 3 panneaux (type 30)"},
{value : "acier7",
         label :  "Acier 3 panneaux, 2 rangs d'ailettes (type 32)"},
];