export default  [
{value : "5",
         label :  "Acier galva à joint longitudinal"},
{value : "4",
         label :  "Acier galva à joint spiral"},
{value : "3",
         label :  "ALU"},
{value : "9",
         label :  "Fexible aluminium polyester"},
{value : "7",
         label :  "Fibre de verre"},
{value : "8",
         label :  "Fibre PVC Armé"},
{value : "6",
         label :  "Flexible alu"},
{value : "1",
         label :  "Inox"},
{value : "2",
         label :  "PVC"}
];