export default  [
{value : "Vitrage12",
         label :  "Double vitrage 16mm argon"},
{value : "Vitrage3",
         label :  "Double vitrage bois"},
{value : "Vitrage6",
         label :  "Double vitrage Bois absorbant"},
{value : "Vitrage4",
         label :  "Double vitrage métal"},
{value : "Vitrage7",
         label :  "Double vitrage métal absorbant"},
{value : "Vitrage5",
         label :  "Double vitrage PVC"},
{value : "Vitrage8",
         label :  "Double vitrage PVC absorbant"},
{value : "Vitrage9",
         label :  "Pavé de verre bois"},
{value : "Vitrage10",
         label :  "Pavé de verre métal"},
{value : "Vitrage11",
         label :  "Pavé de verre PVC"},
{value : "Vitrage0",
         label :  "Simple vitrage bois"},
{value : "Vitrage1",
         label :  "Simple vitrage métal"},
{value : "Vitrage2",
         label :  "Simple vitrage PVC"}
];